name: Docker Image MySQL
on: workflow_dispatch
jobs:
  mysql:
    name: MySQL
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: mysql
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
