name: Docker Image Redis
on: workflow_dispatch
jobs:
  redis:
    name: Redis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: redis
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
