name: PHP for M2 with xDebug

on:
  workflow_dispatch:
    inputs:
      xdebug3:
        description: "xDebug 3 (latest)"
        default: '0'
        required: false
      xdebug2:
        description: "xDebug 2"
        default: '0'
        required: false

jobs:
  xdebug3:
    if: ${{ github.event.inputs.xdebug3 == '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/magento2/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            drpayyne/warden-php-m2-xdebug3:7.4
            ghcr.io/drpayyne/warden-php-m2-xdebug3:7.4
            ghcr.io/drpayyne/warden-php-m2-xdebug3:latest
  xdebug2:
    if: ${{ github.event.inputs.xdebug2== '1' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/magento2/debug/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            drpayyne/warden-php-m2-xdebug2:7.4
            ghcr.io/drpayyne/warden-php-m2-xdebug2:7.4
            ghcr.io/drpayyne/warden-php-m2-xdebug2:latest
